name: CI
on: push
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: actionshub/markdownlint@v3.1.4

      - name: Perl Syntaxcheck
        run: perl -Mstrict -cw *.pl
