name: CI
on: push
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Markdown lint
        uses: actionshub/markdownlint@2.0.2

      - name: Perl Syntaxcheck
        run: perl -Mstrict -cw *.pl
